[platformio]
# Avisa o VS Code para usar o arquivo .ino como o código principal
src_dir = . 

[env:esp32dev]
platform = espressif32
board = esp32dev
framework = arduino
monitor_speed = 115200

# LISTA DE BIBLIOTECAS: O PlatformIO baixa tudo sozinho ao compilar!
lib_deps =
    sandeepmistry/LoRa @ ^0.8.0      # Biblioteca para o rádio LoRa SX1278
    bogde/HX711 @ ^0.7.5             # Biblioteca para a Célula de Carga