[platformio]
# Avisa o VS Code para usar o arquivo .ino como o código principal
src_dir = . 

[env:esp32dev]
platform = espressif32
board = esp32dev
framework = arduino
monitor_speed = 115200

lib_deps =
    mikem/RadioHead
    bogde/HX711 @ ^0.7.5             # Biblioteca para a Célula de Carga